switch to prek (#1713)
Much faster than pre-commit!

---------

Co-authored-by: Jordan Carlin <jordanmcarlin@gmail.com>

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -239,54 +239,25 @@ if [ ! -v GITHUB_ACTIONS ]; then
   if [ ! -f "$GIT_REPO_ROOT/hooks/pre-commit" ]; then
     cat << HOOK > "$GIT_REPO_ROOT/hooks/pre-commit"
 #!/usr/bin/env bash
-# File generated by pre-commit: https://pre-commit.com
-# ID: 138fd403232d2ddd5efb44317e38bf03
 
 # start templated
-INSTALL_PYTHON=\$(realpath ./bin/python)
+INSTALL_PREK=\$(realpath ./bin/prek)
 ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
 # end templated
 
 GIT_REPO_ROOT=$(git rev-parse --show-toplevel | tr -d '\n')
 HERE="$(cd "$(dirname "\$0")" && pwd)"
 ARGS+=(--hook-dir "\$HERE" -- "\$@")
-export PRE_COMMIT_HOME=${GIT_REPO_ROOT}/.cache
 
-if [ -x "\$INSTALL_PYTHON" ]; then
-    exec "\$INSTALL_PYTHON" -mpre_commit "\${ARGS[@]}"
-elif command -v pre-commit > /dev/null; then
-    exec pre-commit "\${ARGS[@]}"
+if [ -x "\$INSTALL_PREK" ]; then
+    exec "\$INSTALL_PREK" "\${ARGS[@]}"
+elif command -v prek > /dev/null; then
+    exec prek "\${ARGS[@]}"
 else
-    echo '\`pre-commit\` not found.  Did you forget to activate your virtualenv?' 1>&2
+    echo '\`prek\` not found.  Did you forget to activate your virtualenv?' 1>&2
     exit 1
 fi
 HOOK
     chmod +x "$GIT_REPO_ROOT/hooks/pre-commit"
-  fi
-
-  if [ ! -f "$GIT_REPO_ROOT/hooks/commit-msg" ]; then
-    cat << HOOK > "$GIT_REPO_ROOT/hooks/commit-msg"
-#!/usr/bin/env bash
-# File generated by pre-commit: https://pre-commit.com
-# ID: 138fd403232d2ddd5efb44317e38bf03
-
-# start templated
-INSTALL_PYTHON=\$(realpath ./bin/python)
-ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=commit-msg)
-# end templated
-
-HERE="$(cd "$(dirname "\$0")" && pwd)"
-ARGS+=(--hook-dir "\$HERE" -- "\$@")
-
-if [ -x "\$INSTALL_PYTHON" ]; then
-    exec "\$INSTALL_PYTHON" -mpre_commit "\${ARGS[@]}"
-elif command -v pre-commit > /dev/null; then
-    exec pre-commit "\${ARGS[@]}"
-else
-    echo '\`pre-commit\` not found.  Did you forget to activate your virtualenv?' 1>&2
-    exit 1
-fi
-HOOK
-    chmod +x "$GIT_REPO_ROOT/hooks/commit-msg"
   fi
 fi
